import pytest

from day08 import find_antinodes, find_antinodes_2, parse_antennas

DATA1 = """..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
.........."""

DATA2 = """..........
..........
..........
....a.....
........a.
.....a....
..........
..........
..........
.........."""

DATA3 = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""


DATA4 = """T...........
...T........
.T..........
............
............
............
............
............
............
............
............
............"""


def test_parse_antennas():
    data = [line.strip() for line in DATA3.splitlines()]

    ret = parse_antennas(data)
    assert ret == {
        "0": [(8, 1), (5, 2), (7, 3), (4, 4)],
        "A": [(6, 5), (8, 8), (9, 9)],
    }


@pytest.mark.parametrize(
    "inp, expected",
    [
        (DATA1, 2),
        (DATA2, 4),
    ],
)
def test_find_antinodes(inp: str, expected: int):
    data = [line.strip() for line in inp.splitlines()]

    antinodes_cnt = find_antinodes(data)

    assert antinodes_cnt == expected


def test_find_antinodes2():

    data = [line.strip() for line in DATA3.splitlines()]

    antinodes_cnt = find_antinodes_2(data)

    assert antinodes_cnt == 34
